# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_urls',
            name='user',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
