# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0002_auto_20161130_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr_urls',
            name='description',
            field=models.CharField(default='No Description', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='usr_urls',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Visits'),
        ),
        migrations.AlterField(
            model_name='usr_urls',
            name='httpurl',
            field=models.URLField(verbose_name='Orginal URL'),
        ),
        migrations.AlterField(
            model_name='usr_urls',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Created Data\\Time'),
        ),
        migrations.AlterField(
            model_name='usr_urls',
            name='short_id',
            field=models.SlugField(max_length=8, primary_key=True, serialize=False, verbose_name='Short URL'),
        ),
    ]
