# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0003_auto_20161207_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usr_urls',
            options={'verbose_name_plural': 'Total URLs'},
        ),
        migrations.RemoveField(
            model_name='usr_urls',
            name='short_id',
        ),
        migrations.AddField(
            model_name='usr_urls',
            name='short_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=50, primary_key=True, serialize=False, verbose_name='Short URL'),
            preserve_default=False,
        ),
    ]
