# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0004_auto_20161211_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr_urls',
            name='short_id',
            field=models.SlugField(default=django.utils.timezone.now, max_length=8, primary_key=True, serialize=False, verbose_name='Short ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usr_urls',
            name='short_url',
            field=models.URLField(max_length=60, verbose_name='Short URL'),
        ),
    ]
